concord-consortium/hurricane-model

src/config.ts
src/models/pressure-system.ts
src/models/simulation.ts

- Tweak model
- setup Azores-Bermuda high scenario
- change pressure system range to the gradient (so later when user changes strength of the system, its range is updated too)

Tweak model, setup Azores-Bermuda high scenario, change pressure system range to gradient

---

package-lock.json
package.json
src/components/map-view.tsx
src/components/pixi-wind-layer.tsx
src/components/pressure-system-icon.scss
src/components/pressure-system-icon.test.tsx
src/components/pressure-system-icon.tsx
src/components/pressure-system-marker.test.tsx
src/components/pressure-system-marker.tsx
src/index.tsx
src/models/pressure-system.ts
src/models/simulation.ts

[#163235660]
Implementation of `src/components/pressure-system-marker.tsx` is a bit tricky. I hope that comments explain the issues well enough, but if it's not clear, let me know and I'll work on comments or the code.

Add pressure system strength sliders and labels

---

package-lock.json
package.json
src/components/hurricane-track.tsx
src/components/map-view.tsx
src/config.ts
src/math-utils.ts
src/models/pressure-system.ts
src/models/simulation.ts
src/types.ts

[#162956992]
I have some simple unit tests, but it seems there's some problem with Leaflet / React leaflet, or I'm doing something wrong. I'll skip it for now, but I'll try to get back to that later.

Render hurricane track

---

src/components/map-view.test.tsx
src/components/map-view.tsx
src/config.ts
src/models/hurricane.test.ts
src/models/hurricane.ts
src/models/simulation.test.ts
src/models/simulation.ts

[#163236960]
Note that it's again based against the previous PR to make diff cleaner.

When Hurricane heads over land or cold water it dissipates and disappears

---

src/components/bottom-bar.tsx
src/config.ts
src/models/ui.ts

[#164420598]
@dstrawberrygirl, these new options should be exposed on the authoring page, as they're important for authors.

Let authors configure bottom bar and initial opacity of layers

---

src/components/bottom-bar.tsx
src/components/map-view.scss
src/components/map-view.tsx

Re-implement return to full map view button using UI prototype spec

---

src/components/bottom-bar.tsx
src/components/map-view.scss
src/components/map-view.tsx

[#164602265]
These buttons are added to DOM in random order by Leaflet so I had to use flex and order property to enforce order we actually want.

Fix styling of map controls (including return to full map button)

---

src/assets/hurricane.svg
src/components/hurricane-marker.scss
src/components/hurricane-marker.tsx

[#164420765]
Hurricane styles and animation update.

Update styles of hurricane icon

---

package-lock.json
package.json
src/components/common.scss
src/components/index-page.test.tsx
src/components/index-page.tsx
src/components/map-view.tsx
src/components/temperature-scale.scss
src/components/temperature-scale.test.tsx
src/components/temperature-scale.tsx

This adds the key for the sea surface temperature overlay [#164420629]

Temperature scale key

---

package-lock.json
src/components/map-button.tsx
src/components/map-view.tsx
src/components/playback-buttons.tsx
src/components/right-panel.tsx
src/config.ts
src/map-layer-tiles.ts
src/models/ui.ts

Work-in-progress on Population overlay - at the moment, overlays are singular (and don't stack). I've used a population map that only covers the US, no key has been created for this yet. Some strange issues regarding map tile offset showed up when toggling the populations before the model was run, so I added a call to reset the map which seemingly fixed it - obviously not the ideal solution, there's probably a better solution to this out there.

Population overlay

---

package-lock.json
package.json
src/components/app.scss
src/components/bottom-bar.scss
src/components/index-page.tsx
src/components/map-view.tsx
src/components/pixi-wind-layer.tsx
src/components/precipitation-layer.tsx
src/global.d.ts
src/models/ui.ts
src/shutterbug-support.ts

Another set of small bug fixes (commit names should be descriptive enough) + Shutterbug support.

Bug fixes and Shutterbug support

---

.travis.yml
package-lock.json
package.json

Since I was unable to get the most recent changes to build on Travis, I've updated package.json to use Trusty, and also updated dependencies to fix warnings. A quick PR for sanity check, project team want to push to production soon.

Fix build errors by using Trusty

---

package-lock.json
src/models/simulation.ts

[#177410554]
It turns out the original version had the same performance issue as the DESE version. This fix increases FPS from ~30 to 60 on my machine.

Improve performance by caching wind data KD Tree

---

.travis.yml
package-lock.json
package.json
src/components/bottom-bar.tsx
src/components/map-button.tsx
src/components/map-view.tsx
src/components/pressure-system-icon.tsx
src/components/pressure-system-marker.tsx
src/components/right-panel.tsx
src/components/season-button.tsx
src/components/top-bar.test.tsx
src/components/top-bar.tsx
src/components/wind-arrows-toggle.tsx

Add logging

---

src/components/bottom-bar.tsx
src/components/hurricane-marker.scss
src/components/map-button.scss
src/components/map-button.tsx
src/components/map-view.tsx
src/components/season-button.scss
src/components/season-button.test.tsx
src/components/season-button.tsx
src/components/sst-key.scss
src/components/sst-key.tsx
src/config.ts
src/models/ui.ts

The final round of style updates, mostly based on Michael's feedback.
1. I've fixed the styling of the hurricane marker, the previous CSS was accidentally removing black outline.
2. Accessible Key checkbox has the correct color and margin now.
3. I've also removed all color blind variable names form the codebase.
4. I've removed hover effects from disabled components.
5. I've tweaked the look of the disabled Season pulldown menu.
Demo: https://hurricane.concord.org/branch/style-update/index.html (soon)

Style update

---

package-lock.json
package.json
src/models/simulation.test.ts

Update version number; npm audit fix

Release 1.5.0

---

src/models/simulation.test.ts

We (I) were resetting the async timeout too early. 😬

Tweak flaky SST test

---

.travis.yml
package-lock.json
package.json
src/components/map-view.test.tsx
src/components/map-view.tsx
src/components/storm-surge-overlay.test.tsx
src/components/storm-surge-overlay.tsx
src/map-layer-tiles.ts

[[#184558292]](https://www.pivotaltracker.com/story/show/184558292)
This PR replaces old storm surge map tiles with a new version.

 update storm surge maps

---

cypress/e2e/integration/basic.test.cy.js
src/components/authoring.tsx
src/components/bottom-bar.scss
src/components/bottom-bar.tsx
src/components/hurricane-image-toggle.scss
src/components/icon-button.scss
src/components/select-button.scss
src/components/select-button.test.tsx
src/components/select-button.tsx
src/components/start-location-button.test.tsx
src/components/start-location-button.tsx
src/components/wind-arrows-toggle.scss
src/config.ts
src/material-ui-theme.tsx
src/models/simulation.test.ts
src/models/simulation.ts
src/types.ts

[HURR-2](https://concord-consortium.atlassian.net/browse/HURR-2)
Adds a "Start Location" select menu for setting the hurricane's initial location. This work is only to add the UI element with minimal functionality. More of the latter will be added in follow-up changes ([related Jira issue](https://concord-consortium.atlassian.net/browse/HURR-3)).
**Acceptance Criteria**
- The new “Start Location” menu appears in the bottom control bar
- Existing items in the bottom control bar make space for this new menu (See [Zeplin specs](https://app.zeplin.io/project/60c9c0d5060353bd2bb10172/screen/675e3f89ed460837ad9dfb67))
- The menu will have two options, "Gulf" and "Atlantic"
- Default selection is "Atlantic"
[HURR-2]: https://concord-consortium.atlassian.net/browse/HURR-2?atlOrigin=eyJpIjoiNWRkNTl …

feat: hurricane start location menu (HURR-2)

---

src/config.ts
src/models/simulation.test.ts
src/models/simulation.ts

[HURR-3](https://concord-consortium.atlassian.net/browse/HURR-3)
[HURR-3]: https://concord-consortium.atlassian.net/browse/HURR-3?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: set initial strength according to start position (HURR-3)
